In [1]:
import numpy as np

In [2]:
array1 = np.random.randint(1, 100, (5, 5))
print(array1)

[[79 16 54 84 72]
 [68 97 20 60 98]
 [81 16 65 93 80]
 [60 97 14 25 51]
 [26 40 81 16 32]]


In [3]:
array2 = np.linspace(2,4,5)
print(array2)

[2.  2.5 3.  3.5 4. ]


In [4]:
np.subtract(array1,array2)

array([[77. , 13.5, 51. , 80.5, 68. ],
       [66. , 94.5, 17. , 56.5, 94. ],
       [79. , 13.5, 62. , 89.5, 76. ],
       [58. , 94.5, 11. , 21.5, 47. ],
       [24. , 37.5, 78. , 12.5, 28. ]])

In [5]:
np.add(array1,array2)

array([[ 81. ,  18.5,  57. ,  87.5,  76. ],
       [ 70. ,  99.5,  23. ,  63.5, 102. ],
       [ 83. ,  18.5,  68. ,  96.5,  84. ],
       [ 62. ,  99.5,  17. ,  28.5,  55. ],
       [ 28. ,  42.5,  84. ,  19.5,  36. ]])

In [6]:
np.divide(array1,array2)

array([[39.5       ,  6.4       , 18.        , 24.        , 18.        ],
       [34.        , 38.8       ,  6.66666667, 17.14285714, 24.5       ],
       [40.5       ,  6.4       , 21.66666667, 26.57142857, 20.        ],
       [30.        , 38.8       ,  4.66666667,  7.14285714, 12.75      ],
       [13.        , 16.        , 27.        ,  4.57142857,  8.        ]])

In [7]:
np.multiply(array1,array2)

array([[158. ,  40. , 162. , 294. , 288. ],
       [136. , 242.5,  60. , 210. , 392. ],
       [162. ,  40. , 195. , 325.5, 320. ],
       [120. , 242.5,  42. ,  87.5, 204. ],
       [ 52. , 100. , 243. ,  56. , 128. ]])

In [8]:
array1.max(axis=0)

array([81, 97, 81, 93, 98])

In [9]:
array1.max(axis=1)

array([84, 98, 93, 97, 81])

In [10]:
array1.max()

98

In [11]:
array2.max()

4.0

In [12]:
array2 = np.resize(array2,(5,5))
print(array2)

[[2.  2.5 3.  3.5 4. ]
 [2.  2.5 3.  3.5 4. ]
 [2.  2.5 3.  3.5 4. ]
 [2.  2.5 3.  3.5 4. ]
 [2.  2.5 3.  3.5 4. ]]
